app:
  name: "school-app"

web:
  replicas: "1"
  port: 3000
  container:
    image: ""
    tag: ""
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: ""
      cpu: ""

api:
  admin:
    replicas: "1"
    port: 9001
    container:
      image: ""
      tag: ""
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        memory: ""
        cpu: ""
  student:
    replicas: "1"
    port: 9002
    container:
      image: ""
      tag: ""
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        memory: ""
        cpu: ""
  teacher:
    replicas: "1"
    port: 9003
    container:
      image: ""
      tag: ""
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        memory: ""
        cpu: ""

db:
  container:
    image: "postgres"
    tag: "latest"
  storageSize: 5G
  port: 5432