apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}-db
spec:
  replicas: 1
  serviceName: {{ .Values.app.name }}-db
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-db
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-db
    spec:
      serviceAccountName: ebs-csi-controller-sa
      containers:
        - name: {{ .Values.app.name }}-db
          image: {{ .Values.db.container.image }}:{{ .Values.db.container.tag }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-db
                  key: admin_postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-db
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-db
                  key: postgres_password
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: gp2
        resources:
          requests:
            storage: {{ .Values.db.storageSize }}