apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: {{ .Values.app.name }}-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}