apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-student-api
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-student-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.student.port }}