apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-teacher-api
spec:
  selector:
    app: {{ .Values.app.name }}-teacher-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.teacher.port }}