apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-web
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-web
  ports:
    - protocol: TCP
      port: {{ .Values.web.port }}